import { z } from 'zod';

export enum MediastackCountry {
  ARGENTINA = 'ar',
  AUSTRALIA = 'au',
  AUSTRIA = 'at',
  BELGIUM = 'be',
  BRAZIL = 'br',
  BULGARIA = 'bg',
  CANADA = 'ca',
  CHINA = 'cn',
  COLOMBIA = 'co',
  CZECH_REPUBLIC = 'cz',
  EGYPT = 'eg',
  FRANCE = 'fr',
  GERMANY = 'de',
  GREECE = 'gr',
  HONG_KONG = 'hk',
  HUNGARY = 'hu',
  INDIA = 'in',
  INDONESIA = 'id',
  IRELAND = 'ie',
  ISRAEL = 'il',
  ITALY = 'it',
  JAPAN = 'jp',
  LATVIA = 'lv',
  LITHUANIA = 'lt',
  MALAYSIA = 'my',
  MEXICO = 'mx',
  MOROCCO = 'ma',
  NETHERLANDS = 'nl',
  NEW_ZEALAND = 'nz',
  NIGERIA = 'ng',
  NORWAY = 'no',
  PHILIPPINES = 'ph',
  POLAND = 'pl',
  PORTUGAL = 'pt',
  ROMANIA = 'ro',
  SAUDI_ARABIA = 'sa',
  SERBIA = 'rs',
  SINGAPORE = 'sg',
  SLOVAKIA = 'sk',
  SLOVENIA = 'si',
  SOUTH_AFRICA = 'za',
  SOUTH_KOREA = 'kr',
  SWEDEN = 'se',
  SWITZERLAND = 'ch',
  TAIWAN = 'tw',
  THAILAND = 'th',
  TURKEY = 'tr',
  UAE = 'ae',
  UKRAINE = 'ua',
  UNITED_KINGDOM = 'gb',
  UNITED_STATES = 'us',
  VENEZUELA = 've',
}

export const MediastackCountrySchema = z.nativeEnum(MediastackCountry);
